"""Import extra athlete facts from downloaded UFC profile HTML (no network)."""
import html
import json
import re
import sys
from pathlib import Path


def clean(value):
    return " ".join(html.unescape(re.sub(r"<[^>]+>", " ", value)).split())


def parse_profile(page):
    bio = dict((clean(label), clean(value)) for label, value in re.findall(
        r'class="c-bio__label">(.*?)</div>\s*<div class="c-bio__text">(.*?)(?=</div>\s*</div>)', page, re.S))
    stats = dict((clean(label), clean(value).replace(" ", "")) for value, label in re.findall(
        r'class="c-stat-compare__number">(.*?)<div class="c-stat-compare__label">(.*?)</div>', page, re.S))
    wins = dict((clean(label), clean(value)) for value, label in re.findall(
        r'athlete-stats__stat-numb">(.*?)</p>\s*<p[^>]*athlete-stats__stat-text">(.*?)</p>', page, re.S))
    def number(value):
        try:
            result = float((value or "").replace("%", ""))
            return result if result >= 0 else None
        except ValueError:
            return None
    def converted(label, factor):
        value = number(bio.get(label))
        return round(value * factor, 1) if value is not None else None
    result = {
        "age": number(bio.get("Age")), "gym": bio.get("Trains at") or None,
        "weightKg": converted("Weight", 0.45359237),
        "legReachCm": converted("Leg reach", 2.54),
        "debut": bio.get("Octagon Debut") or None,
    }
    for key, label in {
        "strikesLanded": "Sig. Str. Landed", "strikesAbsorbed": "Sig. Str. Absorbed",
        "takedownAverage": "Takedown avg", "submissionAverage": "Submission avg",
        "strikingDefense": "Sig. Str. Defense", "takedownDefense": "Takedown Defense",
        "knockdownAverage": "Knockdown Avg",
    }.items():
        result[key] = number(stats.get(label))
    for key, label in {"strikingAccuracy": "Striking accuracy", "takedownAccuracy": "Takedown Accuracy"}.items():
        match = re.search(r"<title>" + label + r"\s+(\d+)%</title>", page, re.I)
        result[key] = int(match[1]) if match else None
    for key, label in {"koWins": "Wins by Knockout", "submissionWins": "Wins by Submission", "firstRoundFinishes": "First Round Finishes"}.items():
        result[key] = number(wins.get(label))
    return result


if __name__ == "__main__":
    folder, manifest, date, destination = sys.argv[1:]
    athletes = json.loads(Path(manifest).read_text())
    result = {}
    for fighter in athletes:
        data = parse_profile((Path(folder) / f"octagon-{fighter['id']}.html").read_text())
        if data["age"] is None or data["strikesLanded"] is None:
            raise ValueError(f"Incomplete profile: {fighter['id']}")
        result[fighter["id"]] = {**data, "source": fighter["source"], "consulted": date}
    Path(destination).write_text("// Official UFC profile snapshot; generated by scripts/import-fighter-info.py.\nexport const fighterInfo = " + json.dumps(result, ensure_ascii=False, indent=2) + ";\n")
